# Generated by Django 3.0.dev20190216065628 on 2019-03-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('zname', '中文名'), ('kname', '科名')], max_length=20)),
                ('queryContent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zname', models.CharField(max_length=64)),
                ('kname', models.CharField(max_length=64)),
            ],
        ),
    ]
