# Generated by Django 3.0.dev20190216065628 on 2019-03-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzTree', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='tree',
            name='biename',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='tree',
            name='bloom_color',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='tree',
            name='bloom_date',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='tree',
            name='fruit_color',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='tree',
            name='fruit_date',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='tree',
            name='ldname',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='tree',
            name='leaf_color',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='tree',
            name='morphology',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='tree',
            name='sname',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AlterField(
            model_name='queryuser',
            name='condition',
            field=models.CharField(choices=[('zname', '中文名'), ('ldname', '拉丁名'), ('kname', '科名'), ('sname', '属名'), ('biename', '别名'), ('morphology', '形态'), ('bloom_date', '花期'), ('bloom_color', '花色'), ('fruit_date', '果期'), ('fruit_color', '果色'), ('leaf_color', '叶色')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tree',
            name='kname',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AlterField(
            model_name='tree',
            name='zname',
            field=models.CharField(default=' ', max_length=64),
        ),
    ]
