# Generated by Django 3.0.dev20190216065628 on 2019-03-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzTree', '0002_auto_20190309_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.CharField(choices=[('1', '1月'), ('2', '2月'), ('3', '3月'), ('4', '4月'), ('5', '5月'), ('6', '6月'), ('7', '7月'), ('8', '8月'), ('9', '9月'), ('10', '10月'), ('11', '11月'), ('12', '12月')], max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='QueryUser',
        ),
        migrations.AlterModelOptions(
            name='tree',
            options={},
        ),
        migrations.RemoveField(
            model_name='tree',
            name='bloom_date',
        ),
        migrations.AddField(
            model_name='tree',
            name='bloom_date',
            field=models.ManyToManyField(to='hzTree.Months'),
        ),
    ]
