# Generated by Django 3.0.dev20190216065628 on 2019-03-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzTree', '0003_auto_20190312_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='months',
            name='months',
            field=models.IntegerField(choices=[(1, '1月'), (2, '2月'), (3, '3月'), (4, '4月'), (5, '5月'), (6, '6月'), (7, '7月'), (8, '8月'), (9, '9月'), (10, '10月'), (11, '11月'), (12, '12月')], max_length=12),
        ),
    ]
