# Generated by Django 3.0.dev20190216065628 on 2019-03-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzTree', '0004_auto_20190312_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='months',
            name='months',
            field=models.IntegerField(max_length=12),
        ),
    ]
