# Generated by Django 3.0.dev20190216065628 on 2019-03-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzTree', '0005_auto_20190312_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='months',
            name='months',
            field=models.CharField(max_length=12),
        ),
    ]
