# Generated by Django 3.0.dev20190216065628 on 2019-03-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzTree', '0006_auto_20190312_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='months',
            old_name='months',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='tree',
            name='bloom_date',
            field=models.ManyToManyField(blank=True, to='hzTree.Months'),
        ),
    ]
