# Generated by Django 3.0.dev20190216065628 on 2019-03-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzTree', '0007_auto_20190312_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='bloom_date',
            field=models.ManyToManyField(blank=True, related_name='bloom_date', to='hzTree.Months'),
        ),
        migrations.RemoveField(
            model_name='tree',
            name='fruit_date',
        ),
        migrations.AddField(
            model_name='tree',
            name='fruit_date',
            field=models.ManyToManyField(blank=True, related_name='fruit_date', to='hzTree.Months'),
        ),
    ]
