# Generated by Django 3.0.dev20190216065628 on 2019-03-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzTree', '0009_auto_20190312_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='months',
            name='name',
            field=models.CharField(max_length=12),
        ),
    ]
