# Generated by Django 3.0.dev20190216065628 on 2019-03-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzTree', '0010_auto_20190312_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='leaf_color_autumn',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='tree',
            name='leaf_color_spring',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='tree',
            name='leaf_color_summer',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='tree',
            name='leaf_color_winter',
            field=models.CharField(default=' ', max_length=64),
        ),
    ]
