# Generated by Django 3.0.dev20190216065628 on 2019-03-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzTree', '0011_auto_20190313_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='tree_type',
            field=models.CharField(choices=[('常绿乔木', '常绿乔木'), ('落叶乔木', '落叶乔木')], default='', max_length=64),
        ),
    ]
