# Generated by Django 3.0.dev20190216065628 on 2019-03-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzTree', '0012_tree_tree_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='bloom_color_autumn',
            field=models.CharField(default='无', max_length=64),
        ),
        migrations.AddField(
            model_name='tree',
            name='bloom_color_spring',
            field=models.CharField(default='无', max_length=64),
        ),
        migrations.AddField(
            model_name='tree',
            name='bloom_color_summer',
            field=models.CharField(default='无', max_length=64),
        ),
        migrations.AddField(
            model_name='tree',
            name='bloom_color_winter',
            field=models.CharField(default='无', max_length=64),
        ),
        migrations.AddField(
            model_name='tree',
            name='fruit_color_autumn',
            field=models.CharField(default='无', max_length=64),
        ),
        migrations.AddField(
            model_name='tree',
            name='fruit_color_spring',
            field=models.CharField(default='无', max_length=64),
        ),
        migrations.AddField(
            model_name='tree',
            name='fruit_color_summer',
            field=models.CharField(default='无', max_length=64),
        ),
        migrations.AddField(
            model_name='tree',
            name='fruit_color_winter',
            field=models.CharField(default='无', max_length=64),
        ),
        migrations.AlterField(
            model_name='tree',
            name='leaf_color_autumn',
            field=models.CharField(default='无', max_length=64),
        ),
        migrations.AlterField(
            model_name='tree',
            name='leaf_color_spring',
            field=models.CharField(default='无', max_length=64),
        ),
        migrations.AlterField(
            model_name='tree',
            name='leaf_color_summer',
            field=models.CharField(default='无', max_length=64),
        ),
        migrations.AlterField(
            model_name='tree',
            name='leaf_color_winter',
            field=models.CharField(default='无', max_length=64),
        ),
    ]
