# Generated by Django 3.0.dev20190216065628 on 2019-03-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzTree', '0014_auto_20190315_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='geo_distribution',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='tree',
            name='pollution_tolerance',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='tree',
            name='propensity',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='tree',
            name='soil',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='tree',
            name='tree_shape',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='tree',
            name='tree_value',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AlterField(
            model_name='tree',
            name='family_name',
            field=models.CharField(default=' ', max_length=16),
        ),
        migrations.AlterField(
            model_name='tree',
            name='genus_name',
            field=models.CharField(default=' ', max_length=16),
        ),
        migrations.AlterField(
            model_name='tree',
            name='species_name',
            field=models.CharField(default=' ', max_length=16),
        ),
        migrations.AlterField(
            model_name='tree',
            name='tree_type',
            field=models.CharField(choices=[('常绿乔木', '常绿乔木'), ('落叶乔木', '落叶乔木')], default='', max_length=16),
        ),
    ]
