# Generated by Django 3.0.dev20190216065628 on 2019-03-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzTree', '0015_auto_20190316_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='tree_type',
            field=models.CharField(default=' ', max_length=16),
        ),
    ]
